export default function Home() {

  const title: string = `RTau's Page`
  const desc: string = `Generated by create next app`

  return (
    <main className="flex min-h-screen flex-col items-center p-24">
      <h1>{ title }</h1>
      <p>{ desc }</p>
    </main>
  );
}
